package main

import "strings"

var table [256]uint32
var tableInitialized bool

func PakStringCrc32(str string) uint32 {
	if !tableInitialized {
		makeCrc32LookupTable()
	}

	str = strings.ToLower(str)
	str = strings.ReplaceAll(str, "\\", "/")

	crc := uint32(0xFFFFFFFF)

	for _, c := range str {
		tableIdx := byte(crc) ^ byte(c)
		crc = (crc >> 8) ^ table[tableIdx]
	}

	return ^crc
}

// the lookup table generated by this function is NOT the same
// as in CRC-32/ISO-HDLC due to a stupid bug in RSBR:
// this function does arithmetic right shifts (where the MSB is kept)
// instead of logical right shifts (where the MSB is 0).
// here we replicate that by casting to a signed integer before doing the shift.
//
// this took me way too long to figure out :(
func makeCrc32LookupTable() {
	for i := range 256 {
		table[i] = uint32(i)

		for range 8 {
			if (table[i] & 1) == 1 {
				table[i] = uint32(int32(table[i])>>1) ^ 0xEDB88320
			} else {
				table[i] = uint32(int32(table[i]) >> 1)
			}
		}
	}

	tableInitialized = true
}

// func ars(num uint32, shift uint32) uint32 {
// 	msb := num & 0x80000000
// 	return (num >> shift) | msb
// }
